<?php
$active_group = 'default';
$active_record = TRUE;
$db['default']['username'] = 'root';
$db['default']['password'] = 'kENhFm7aYdCdpcm';
$db['default']['hostname'] = 'conekta-callcentre.copfveobbvrt.us-east-1.rds.amazonaws.com';
$db['default']['database'] = 'openvbx';
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
/* Autogenerated Configuration for db 2015-05-21 */
